[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fdns-format"
version = "0.1.0"

edition = "2018"

[dependencies]
anyhow = "1"
byteorder = "1"
cast = "0.2"

[dependencies.nom]
version = "4"
#features = ["nightly", "verbose-errors"]
