[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fdns"
version = "0.1.0"

[dependencies]
byteorder = "1"
error-chain = "0.11"
mio = "0.6"

[dependencies.nom]
features = ["nightly"]
version = "3"
