[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fdns"
version = "0.1.0"

edition = "2018"

[dependencies]
anyhow = "1"
cast = "0.2"
mio = "0.6"
fdns-format = { path = "../format" }
